name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials (assuming secrets are set)
        run: |
          mkdir -p ~/.aws
          echo "[terradmin]" >> ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "AWS_PROFILE=terradmin" >> $GITHUB_ENV  # Add AWS_PROFILE to environment
          cat $GITHUB_ENV  # Print environment variables for debugging

      - name: Verify AWS credentials (optional)
        run: aws sts get-caller-identity --profile terradmin || true  # Suppress error for workflow continuation

      - name: Terraform init
        run: terraform init
        working-directory: dev

      - name: Terraform plan
        run: terraform plan -out=tfplan
        working-directory: dev

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
        working-directory: dev
        env:
          AWS_PROFILE: terradmin
