name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      #   run: |
      #     mkdir -p ~/.aws
      #     echo "[terradmin]" >> ~/.aws/credentials
      #     echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
      #     echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
      #     cat ~/.aws/credentials  # For debugging
      #     aws configure list  # List AWS CLI configuration for debugging

      - name: Verify AWS credentials
        run: |
          aws sts get-caller-identity --profile terradmin  # Validate AWS credentials

      - name: Terraform init
        run: terraform init
        working-directory: dev

      - name: Terraform plan
        run: terraform plan -out=tfplan
        working-directory: dev
        env:
          AWS_PROFILE: terradmin

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
        working-directory: dev
        env:
          AWS_PROFILE: terradmin
